(function initSkills(global) {
  const ns = (global.WWP = global.WWP || {});

  // Configure and extend this dictionary to tune matching behavior.
  const SKILLS_DICTIONARY = [
    { key: "javascript", aliases: ["javascript", "js", "ecmascript"], category: "language", baseWeight: 1.1 },
    { key: "typescript", aliases: ["typescript", "ts"], category: "language", baseWeight: 1.1 },
    { key: "python", aliases: ["python", "py"], category: "language", baseWeight: 1.1 },
    { key: "java", aliases: ["java"], category: "language", baseWeight: 1.0 },
    { key: "kotlin", aliases: ["kotlin"], category: "language", baseWeight: 1.0 },
    { key: "swift", aliases: ["swift"], category: "language", baseWeight: 1.0 },
    { key: "r", aliases: ["r language", "r programming"], category: "language", baseWeight: 0.9 },
    { key: "matlab", aliases: ["matlab"], category: "language", baseWeight: 0.9 },
    { key: "c", aliases: ["c programming", "language c", "c/c++"], category: "language", baseWeight: 0.9 },
    { key: "c++", aliases: ["c++", "cpp", "c/c++", "c ++"], category: "language", baseWeight: 1.0 },
    { key: "c#", aliases: ["c#", "c sharp"], category: "language", baseWeight: 1.0 },
    { key: "go", aliases: ["golang", "go"], category: "language", baseWeight: 1.0 },
    { key: "rust", aliases: ["rust"], category: "language", baseWeight: 1.0 },
    { key: "sql", aliases: ["sql", "structured query language", "tsql"], category: "database", baseWeight: 1.1 },
    { key: "postgresql", aliases: ["postgresql", "postgres"], category: "database", baseWeight: 1.0 },
    { key: "mysql", aliases: ["mysql"], category: "database", baseWeight: 0.95 },
    { key: "mongodb", aliases: ["mongodb", "mongo db"], category: "database", baseWeight: 0.95 },
    { key: "firebase", aliases: ["firebase", "firestore"], category: "database", baseWeight: 0.9 },
    { key: "dynamodb", aliases: ["dynamodb"], category: "database", baseWeight: 0.9 },
    { key: "elasticsearch", aliases: ["elasticsearch", "elastic search"], category: "database", baseWeight: 0.9 },
    { key: "postgis", aliases: ["postgis"], category: "database", baseWeight: 0.95 },
    { key: "redis", aliases: ["redis"], category: "database", baseWeight: 0.95 },
    { key: "supabase", aliases: ["supabase"], category: "database", baseWeight: 0.95 },
    { key: "html", aliases: ["html", "html5"], category: "frontend", baseWeight: 0.8 },
    { key: "css", aliases: ["css", "css3", "sass", "scss"], category: "frontend", baseWeight: 0.8 },
    { key: "tailwind css", aliases: ["tailwind", "tailwind css"], category: "frontend", baseWeight: 0.95 },
    { key: "react", aliases: ["react", "reactjs", "react.js"], category: "frontend", baseWeight: 1.1 },
    { key: "vue", aliases: ["vue", "vuejs", "vue.js"], category: "frontend", baseWeight: 1.0 },
    { key: "angular", aliases: ["angular"], category: "frontend", baseWeight: 1.0 },
    { key: "next.js", aliases: ["next.js", "nextjs"], category: "frontend", baseWeight: 1.0 },
    { key: "react native", aliases: ["react native"], category: "frontend", baseWeight: 1.0 },
    { key: "svelte", aliases: ["svelte", "sveltekit"], category: "frontend", baseWeight: 0.95 },
    { key: "vite", aliases: ["vite"], category: "frontend", baseWeight: 0.9 },
    { key: "hono", aliases: ["hono"], category: "backend", baseWeight: 0.9 },
    { key: "node.js", aliases: ["node.js", "nodejs", "node"], category: "backend", baseWeight: 1.1 },
    { key: "express", aliases: ["express", "express.js"], category: "backend", baseWeight: 0.9 },
    { key: "nestjs", aliases: ["nestjs", "nest.js", "nest js"], category: "backend", baseWeight: 0.95 },
    { key: "django", aliases: ["django"], category: "backend", baseWeight: 1.0 },
    { key: "flask", aliases: ["flask"], category: "backend", baseWeight: 0.9 },
    { key: "fastapi", aliases: ["fastapi", "fast api"], category: "backend", baseWeight: 1.0 },
    { key: "ruby on rails", aliases: ["ruby on rails", "rails"], category: "backend", baseWeight: 0.9 },
    { key: "laravel", aliases: ["laravel"], category: "backend", baseWeight: 0.9 },
    { key: ".net", aliases: [".net", "dotnet", "asp.net", "aspnet"], category: "backend", baseWeight: 0.95 },
    { key: "spring", aliases: ["spring", "spring boot"], category: "backend", baseWeight: 1.0 },
    { key: "graphql", aliases: ["graphql"], category: "backend", baseWeight: 1.0 },
    { key: "rest api", aliases: ["rest api", "restful api", "restful apis"], category: "backend", baseWeight: 0.72 },
    { key: "openai api", aliases: ["openai", "openai api", "openai apis"], category: "ai", baseWeight: 1.0 },
    { key: "networkx", aliases: ["networkx"], category: "data", baseWeight: 0.9 },
    { key: "git", aliases: ["git", "github", "gitlab", "bitbucket"], category: "tool", baseWeight: 0.9 },
    { key: "docker", aliases: ["docker", "containerization", "containers"], category: "tool", baseWeight: 1.0 },
    { key: "kubernetes", aliases: ["kubernetes", "k8s"], category: "tool", baseWeight: 1.0 },
    { key: "prisma", aliases: ["prisma"], category: "tool", baseWeight: 0.9 },
    { key: "postman", aliases: ["postman"], category: "tool", baseWeight: 0.85 },
    { key: "drupal", aliases: ["drupal", "drupal 8"], category: "tool", baseWeight: 0.85 },
    { key: "fusion 360", aliases: ["fusion 360"], category: "tool", baseWeight: 0.8 },
    { key: "figma", aliases: ["figma"], category: "tool", baseWeight: 0.85 },
    { key: "jira", aliases: ["jira"], category: "tool", baseWeight: 0.8 },
    { key: "linux", aliases: ["linux", "unix"], category: "tool", baseWeight: 0.9 },
    { key: "aws", aliases: ["aws", "amazon web services"], category: "cloud", baseWeight: 1.0 },
    { key: "gcp", aliases: ["gcp", "google cloud"], category: "cloud", baseWeight: 1.0 },
    { key: "azure", aliases: ["azure", "microsoft azure"], category: "cloud", baseWeight: 1.0 },
    { key: "terraform", aliases: ["terraform"], category: "devops", baseWeight: 1.0 },
    { key: "ci/cd", aliases: ["ci/cd", "continuous integration", "continuous delivery", "jenkins", "github actions"], category: "devops", baseWeight: 0.9 },
    { key: "pandas", aliases: ["pandas"], category: "data", baseWeight: 1.0 },
    { key: "numpy", aliases: ["numpy"], category: "data", baseWeight: 1.0 },
    { key: "scikit-learn", aliases: ["scikit-learn", "sklearn"], category: "data", baseWeight: 1.0 },
    { key: "tensorflow", aliases: ["tensorflow", "tf"], category: "ml", baseWeight: 1.0 },
    { key: "pytorch", aliases: ["pytorch"], category: "ml", baseWeight: 1.0 },
    { key: "llm", aliases: ["llm", "large language model", "large language models"], category: "ml", baseWeight: 0.95 },
    { key: "spark", aliases: ["spark", "apache spark", "pyspark"], category: "data", baseWeight: 1.0 },
    { key: "hadoop", aliases: ["hadoop"], category: "data", baseWeight: 0.9 },
    { key: "tableau", aliases: ["tableau"], category: "analytics", baseWeight: 0.9 },
    { key: "power bi", aliases: ["power bi", "powerbi"], category: "analytics", baseWeight: 0.9 },
    { key: "excel", aliases: ["excel", "microsoft excel"], category: "analytics", baseWeight: 0.8 },
    { key: "etl", aliases: ["etl", "data pipeline", "pipelines"], category: "data", baseWeight: 0.9 },
    { key: "data analysis", aliases: ["data analysis", "analytical", "analytics"], category: "analytics", baseWeight: 0.9 },
    { key: "machine learning", aliases: ["machine learning", "ml model", "modeling"], category: "ml", baseWeight: 1.0 },
    { key: "nlp", aliases: ["nlp", "natural language processing"], category: "ml", baseWeight: 0.9 },
    { key: "computer vision", aliases: ["computer vision", "cv"], category: "ml", baseWeight: 0.9 },
    { key: "product management", aliases: ["product management", "product manager", "pm"], category: "role", baseWeight: 1.0 },
    { key: "software engineering", aliases: ["software engineer", "software engineering", "swe", "software developer"], category: "role", baseWeight: 1.0 },
    { key: "firmware", aliases: ["firmware", "embedded firmware"], category: "role", baseWeight: 0.9 },
    { key: "embedded systems", aliases: ["embedded systems", "embedded", "ecu"], category: "role", baseWeight: 0.95 },
    { key: "data analyst", aliases: ["data analyst", "business analyst", "analytics intern"], category: "role", baseWeight: 1.0 },
    { key: "data scientist", aliases: ["data scientist", "data science"], category: "role", baseWeight: 1.0 },
    { key: "backend engineering", aliases: ["backend", "back-end", "server-side"], category: "role", baseWeight: 1.0 },
    { key: "frontend engineering", aliases: ["frontend", "front-end", "ui engineering"], category: "role", baseWeight: 1.0 },
    { key: "full stack", aliases: ["full stack", "full-stack"], category: "role", baseWeight: 1.0 },
    { key: "mobile development", aliases: ["android", "ios", "react native", "swift", "kotlin", "mobile"], category: "role", baseWeight: 0.9 },
    { key: "testing", aliases: ["unit test", "integration test", "qa", "jest", "cypress"], category: "tool", baseWeight: 0.8 },
    { key: "can/lin", aliases: ["can/lin", "can lin", "can bus", "lin bus"], category: "tool", baseWeight: 0.85 },
    { key: "accessibility", aliases: ["accessibility", "wcag", "aria"], category: "tool", baseWeight: 0.9 },
    { key: "agile", aliases: ["agile", "scrum", "kanban"], category: "process", baseWeight: 0.7 },
    { key: "communication", aliases: ["communication", "presentation", "stakeholder"], category: "soft-skill", baseWeight: 0.5 },
    { key: "leadership", aliases: ["leadership", "mentor", "ownership"], category: "soft-skill", baseWeight: 0.5 },
    { key: "problem solving", aliases: ["problem solving", "critical thinking", "analytical thinking"], category: "soft-skill", baseWeight: 0.6 },
    { key: "finance", aliases: ["finance", "financial analysis", "valuation"], category: "domain", baseWeight: 0.8 },
    { key: "marketing", aliases: ["marketing", "seo", "content strategy"], category: "domain", baseWeight: 0.8 },
    { key: "cybersecurity", aliases: ["cybersecurity", "security", "infosec"], category: "domain", baseWeight: 0.9 }
  ];

  ns.SKILLS_DICTIONARY = SKILLS_DICTIONARY;
})(globalThis);
